### PR TITLE
Make sytemd service more resilient

### PR DESCRIPTION
**Pull request by AZMCode**
- ```After=network-online.target```
    - to make sure the script will be able to reach the network.
- ```Type=simple Restart=on-failure RestartSec=10s ExecStartPre=/usr/sbin/ec2-init ExecStart=/usr/bin/true```
    -    To retry script on failure to run

### CODE REVIEW

**Comment by sormy** [comment]
Could you please justify why do you want to automatically restart it? I guess we can tune some things without requirement to make service to respawn again and again. There is a performance impact of such behavior and for service that is considered to be running once during initial provision I guess it is a too high impact.

**Comment by AZMCode** [comment]
Because I found out that during initialization in some instances i had the initialization data could not be fetched for some reason ( at least the systemctl status log said something along those lines ), but worked fine upon later manual execution, so I thought making the whole script more resilient to temporary failures in the network could be beneficial. I understand there are more important tradeoffs to make in this case, however, and am willing to close the pull request if that is the case.

**Comment by sormy** [comment]
What version of ec2-init did you experience issues with? Especially, `CURL_OPTS`.
I have recently updated settings to `CURL="${CURL:-curl --silent --max-time 1 --retry-delay 1 --retry 10 --retry-all-errors --fail}"`. It should give more time for script to get network up and get metadata.

There was an issue with previous versions. `gentoo-ami-builder` caches ec2-init so your cache could have a stale version.

**Comment by AZMCode** [comment]
I did use gentoo-ami-builder, so that could be the case. I currently cannot test which version I used, but I assume that is the case. Will come back to this when I can test this.

**Comment by sormy** [comment]
Check what version of `ec2-init` is inside `gentoo-ami-builder/cache`. If it is old, just remove `cache dir so next bootstrap will download actual version. I should probably remove caching from `gentoo-ami-builder` if it causes confusion.

**Comment by AZMCode** [comment]
1.0.3 in my case

**Comment by sormy** [comment]
Yes, try 1.0.4. It has tuned CURL options.

**Comment by AZMCode** [comment]
Understandable. I'll close the issue then. Thanks for the support!

**Pull request closed without merging**
